version: '3.8'

services:
  db:
    build: 
      context: ./srcs/database/
      dockerfile: Dockerfile
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:  #named volume
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - blockchain_network
    
  backend:
    build: 
      context: ./srcs/backend/
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - .env
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app
    depends_on:
      - db
      - ganache
    networks:
      - blockchain_network

  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    command:
      - --wallet.deterministic
      - --chain.networkId=1337
      - --chain.chainId=1337
      - --server.host=0.0.0.0
    networks:
      - blockchain_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./srcs/frontend/conf/nginx.conf:/etc/nginx/nginx.conf  # Custom NGINX config
      - ./srcs/frontend/workdir:/usr/share/nginx/html  # Frontend files
      - ./certs:/etc/nginx/certs:ro  # SSL certificates (read-only)
    depends_on:
      - backend
    env_file:
      - .env  # Load environment variables
    networks:
      - blockchain_network
    
volumes:
  db_data:
  backend_data:

networks:
  blockchain_network:
    driver: bridge